version: 2
updates:
  - directory: /client
    package-ecosystem: 'npm'
    schedule:
      interval: 'monthly'
      time: '04:00'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
  - directory: /e2e-tests
    package-ecosystem: 'npm'
    schedule:
      interval: 'monthly'
      time: '04:00'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
  - directory: /server
    package-ecosystem: 'npm'
    schedule:
      interval: 'monthly'
      time: '04:00'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
