version: '3'
services:
  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - ./service:/scripts
    ports:
      - 8000:8000
    networks:
      - toto-game-net
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    env_file:
      - ./server/.env
    networks:
      - toto-game-net
  chat:
    build:
      context: ./chat
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./chat/src:/home/node/app/src
      - ./chat/nodemon.json:/home/node/app/nodemon.json
    container_name: chat
    expose:
      - '9000'
    ports:
      - '9000:9000'
    command: npm run dev
    networks:
      - toto-game-net
networks:
  toto-game-net:
    driver: bridge