version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    env_file:
      - ./.env
    volumes:
      - mongo-db:/data/db
    networks:
      - toto-game-net
  go-service:
    build:
      context: ./go-service
      dockerfile: Dockerfile
    container_name: toto-go-service
    hostname: toto-go-service
    ports:
      - 9090:9090
    depends_on:
      - mongodb
      - mongodb-seed
    networks:
      - toto-game-net
  mongodb-seed:
    build:
      context: ./mongodb-seed
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    networks:
      - toto-game-net
  service:
    build:
      context: ./python-service
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - ./python-service:/scripts
    ports:
      - 8000:8000
    networks:
      - toto-game-net
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  totodb:
    image: postgres:13
    ports:
      - 5434:5432
    env_file:
      - ./server/.env
    networks:
      - toto-game-net
networks:
  toto-game-net:
    driver: bridge

volumes:
  mongo-db:
