openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in HTML.
  version: 0.1.9
servers:
  - url: localhost:4000/api/v2
    description: ErPaSitoto Server
paths:
  /players:
    get:
      summary: Get all players.
      description: Returns a list of players.
      responses:
        '200':
          description: Successful getting all players
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  results:
                    type: integer
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Player'
        '404':
          description: Unsuccesful response!
  /players/{id}:
    delete:
      summary: Delete a player
      description: The admin can delete a player
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the player to delete.
          schema:
            type: string
      responses:
        '200':
          description: Successful removing of player
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: string
                  message:
                    type: string
        '500':
          description: Unsuccesful response
  /players/signup:
    post:
      summary: Sign up a player.
      description: Returns a list of players.
      responses:
        '200':
          description: Successful signing up player
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  results:
                    type: integer
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Player'
        '404':
          description: No players found!
  /teams:
    get:
      summary: Returns a list of teams.
      description: Players select one of these teams on signup.
      responses:
        '200': # status code
          description: Successful getting all teams
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  results:
                    type: integer
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Team'
        '500':
          description: No teams found, please try again later
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
  /fixtures/{id}:
    get:
      summary: Returns a fixture by ID.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the fixture to return.
          schema:
            type: integer
            minimum: 707179
      responses:
        '200':
          description: A fixture  with the scores of the players.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    example: success
                  data:
                    properties:
                      fixture:
                        $ref: '#/components/schemas/Fixture'
                      scores:
                        $ref: '#/components/schemas/PredictionsWithScores'
        '400':
          description: Bad request, return error when the id is not valid.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    example: fail
                  message:
                    example: This is not a valid fixture id.

        '404':
          description: The fixture with this id was not found.
        default:
          description: Unexpected error
components:
  schemas:
    Fixture:
      type: object
      properties:
        id:
          type: integer
        homeTeamId:
          type: integer
        homeTeamName:
          type: string
        homeTeamLogo:
          type: string
        goalsHomeTeam:
          type: integer
        awayTeamId:
          type: integer
        awayTeamName:
          type: string
        awayTeamLogo:
          type: string
        goalsAwayTeam:
          type: integer
        eventTimeStamp:
          type: integer
        round:
          type: string
        status:
          type: string
    Team:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        logo:
          type: string
    PredictionsWithScores:
      type: object
      properties:
        name:
          type: string
        id:
          type: string
        pGoalsHomeTeam:
          type: integer
        pGoalsAwayTeam:
          type: integer
        score:
          type: integer
    Player:
      type: object
      properties:
        id:
          type: string
        userName:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        admin:
          type: boolean
        totaalToto:
          type: boolean
        team:
          $ref: '#/components/schemas/Team'
