const bcrypt = require('bcrypt');

const SALT_ROUNDS = Number(process.env.SALT_ROUNDS);

const users = [
  {
    userName: 'Rick',
    firstName: 'Rick',
    lastName: 'Wolt',
    email: 'rick@rick.com',
    password: bcrypt.hashSync('rick123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: true,
    teamId: 206,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'Siffy',
    firstName: 'Sifan',
    lastName: 'Hassan',
    email: 'sifan@hassan.com',
    password: bcrypt.hashSync('sifan123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: false,
    teamId: 1118,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'Fjodjee',
    firstName: 'Fjodor',
    lastName: 'Dostojewski',
    email: 'fjodor@dostojewski.com',
    password: bcrypt.hashSync('fjodor123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: true,
    teamId: 195,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'Jack',
    firstName: 'Jack',
    lastName: 'Sparrow',
    email: 'jack@sparrow.com',
    password: bcrypt.hashSync('jack123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: true,
    teamId: 414,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'Gene',
    firstName: 'Gene',
    lastName: 'Simmons',
    email: 'gene@simmons.com',
    password: bcrypt.hashSync('gene123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: true,
    teamId: 1118,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'Ali',
    firstName: 'Ali',
    lastName: 'Aldi',
    email: 'ali@aldi.com',
    password: bcrypt.hashSync('ali123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: true,
    teamId: 1118,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'Jane',
    firstName: 'Jane',
    lastName: 'Doe',
    email: 'jane@doe.com',
    password: bcrypt.hashSync('jane123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: true,
    teamId: 1118,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'John',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john@doe.com',
    password: bcrypt.hashSync('john123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: true,
    teamId: 1118,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'Mark',
    firstName: 'Mark',
    lastName: 'Rutte',
    email: 'mark@rutte.com',
    password: bcrypt.hashSync('rutte123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: true,
    teamId: 1118,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'Piet',
    firstName: 'Piet',
    lastName: 'Snot',
    email: 'piet@snotte.com',
    password: bcrypt.hashSync('piet123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: true,
    teamId: 1118,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'Leo',
    firstName: 'Leo',
    lastName: 'Messi',
    email: 'leo@messi.com',
    password: bcrypt.hashSync('leo123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: true,
    teamId: 1118,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'Nikolas',
    firstName: 'Nikolas',
    lastName: 'Wiggins',
    email: 'nikolas@wiggins.com',
    password: bcrypt.hashSync('wiggins123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: true,
    teamId: 1118,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'Gael',
    firstName: 'Gael',
    lastName: 'Ruiz',
    email: 'Gael@Ruiz.com',
    password: bcrypt.hashSync('gael123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: false,
    teamId: 1118,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'Anne',
    firstName: 'Ann',
    lastName: 'Baron',
    email: 'anne@barron.com',
    password: bcrypt.hashSync('anne123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: true,
    teamId: 1118,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'Daisy',
    firstName: 'Daisy',
    lastName: 'Garner',
    email: 'daisy@garner.com',
    password: bcrypt.hashSync('daisy123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: false,
    teamId: 1118,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'Keira',
    firstName: 'Keira',
    lastName: 'Petersen',
    email: 'keira@petersen.com',
    password: bcrypt.hashSync('keira123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: true,
    teamId: 1118,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'Denzel',
    firstName: 'Denzel',
    lastName: 'Chan',
    email: 'denzel@chan.com',
    password: bcrypt.hashSync('denzel123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: false,
    teamId: 1118,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'Hailey',
    firstName: 'Hailey',
    lastName: 'Fraizor',
    email: 'hailey@fraizor.com',
    password: bcrypt.hashSync('hailey123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: true,
    teamId: 1118,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'April',
    firstName: 'April',
    lastName: 'Bright',
    email: 'april@bright.com',
    password: bcrypt.hashSync('april123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: true,
    teamId: 1118,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'Antony',
    firstName: 'Antony',
    lastName: 'Li',
    email: 'antony@li.com',
    password: bcrypt.hashSync('antony123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: true,
    teamId: 1118,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'Jack2',
    firstName: 'Jack',
    lastName: 'Kerouac',
    email: 'jack@kerouac.com',
    password: bcrypt.hashSync('jack123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: false,
    teamId: 1118,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'Aiden',
    firstName: 'Aiden',
    lastName: 'Miles',
    email: 'aiden@miles.com',
    password: bcrypt.hashSync('aiden123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: true,
    teamId: 1118,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'Melissa',
    firstName: 'Melissa',
    lastName: 'Clark',
    email: 'melissa@clark.com',
    password: bcrypt.hashSync('melissa123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: true,
    teamId: 1118,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'Erny',
    firstName: 'Erny',
    lastName: 'Beuting',
    email: 'beutham@gmail.com',
    password: bcrypt.hashSync('erny123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: true,
    teamId: 1118,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'Simon',
    firstName: 'Simon',
    lastName: 'Duinmaijer',
    email: 'sj.duinmaijer@gmail.com',
    password: bcrypt.hashSync('simon123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: true,
    teamId: 1118,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'Jauylan',
    firstName: 'Jauylan',
    lastName: 'Khan',
    email: 'jauylan@khan.com',
    password: bcrypt.hashSync('jauylan123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: true,
    teamId: 1118,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'Finn',
    firstName: 'Finn',
    lastName: 'Woodward',
    email: 'finn@woodward.com',
    password: bcrypt.hashSync('finn123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: true,
    teamId: 1118,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'Kane',
    firstName: 'Kane',
    lastName: 'Braak',
    email: 'kane@braak.com',
    password: bcrypt.hashSync('kane123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: true,
    teamId: 1118,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'Suzy',
    firstName: 'Suzan',
    lastName: 'Matt',
    email: 'suzan@matt.com',
    password: bcrypt.hashSync('suzan123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: false,
    teamId: 1118,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userName: 'Steve',
    firstName: 'Steve',
    lastName: 'City',
    email: 'steve@city.com',
    password: bcrypt.hashSync('steve123', SALT_ROUNDS),
    phoneNumber: '0612345678',
    admin: false,
    totaalToto: false,
    teamId: 1118,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

module.exports = users;
